### ISSUE TITLE
You should use music-metadata

### ISSUE THREAD

**Issue by Borewit** [Ankumo/Audy#1]
musicmetadata is depricated, use [music-metadata](https://github.com/Borewit/music-metadata) instead, which also has wav support.

Good luck with your project.

**Comment by Ankumo** [comment]
I know that. I've seen your further version of metadata parser too, but i've decided to use leetreveil version due to easier and purest way to retrieve music album images. Thanks for your advice, however is there any real speed difference or anything else why i should use your module instead?

**Comment by Borewit** [comment]
> easier and purest way

Why is is easier?
API is similar, there are few more options.

Pure? The fact that you may get 0 or multiple callbacks when there really should be getting one and only one, is that the pure feeling?

> real speed difference

No, there both pretty fast, should not be a drastic difference. Depends on the scenario, with direct file access it may be faster, because it skips data. Music-metadata has read everything. Also the streaming architecture is better in music-metadata, up to current node standards.
But it does extracts a lot more information and there it will loose a bit.
Music-metadata is slower in combination with poor quality MP3's (frame sync errors), due to the promise based architecture.

There are tons of reasons,:
- it's better in extracting images:
  - has better support for image type (front, back)
   - has MIME-type support to specify the image type
 - it's ~2 years of development starting when musicmetadata was abandoned
- bugs are usually addressed 1 or 2 days
- supports direct file access
- supports more formats
- supports more tag headers
- has about 20x more generic mapped fields you access (metadata.common)
- can get more information of the audio track duration, samplerate, bitrate etc

**Comment by Ankumo** [comment]
> API is similar, 

You're using promises, but i'd rather use basic stream-like API and keep all promises stuff on myself.
> there are few more options.

To be precise there are TONS of options which i don't need, and
> Depends on the scenario, with direct file access it may be faster, because it skips data.

there is no secret it'd be slower. Even if there is no such difference, the only reason i'm using music metadata parser is to retrieve album image.

> Pure?

I meant syntax

> The fact that you may get 0 or multiple callbacks when there really should be getting one and only one, is that the pure feeling?

Tested it million times, never gets lucky with this kind of bug.

If i'll really need some of your module features or if there will be any real issue with the callbacks or other buggy stuff, i'll change my mind. But for now there is no reason i should use your module instead. I'm really appreciate you're doing great job on this module, sorry
